@startuml
!define COLOR_A_1 #fee0b6
!define COLOR_B_1 #d8daeb
!define COLOR_B_4 #542788
!define COLOR_REL_LINE #8073ac
!define COLOR_REL_TEXT #8073ac

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define GCPPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-icons-GCP/master/dist
!include GCPPuml/GCPCommon.puml
!include GCPPuml/AI_and_Machine_Learning/all.puml
!include GCPPuml/API_Management/all.puml
!include GCPPuml/Compute/all.puml
!include GCPPuml/Databases/all.puml


Person_Ext(user, "User", "interacts with the assistant system")

System_Ext(external,"External Applications", "e-mail, calendar, phone apps, search engine, ")
Enterprise_Boundary(mainSystem,"Sadgamaya") {
    SystemDb(storage,"Storage","stores relevant data - user requests")
    System(dialogFlow,"Dialog Flow","voice Interface",$sprite="Dialog_Flow_Enterprise_Edition")
    System(integrator,"GKE","Connector Service",$sprite="Kubernetes_Engine")
        
    System(authentication,"Auth")
    System(observability,"Observability")    
        
    
    System_Ext(artificialIntelligence,"AI Agent","interfaces human language and programmatic language",$sprite = "robot" )

    
}

Rel_D(user, dialogFlow, "Queries", "Voice/Text")
Rel_U(dialogFlow,user , "Responds", "Voice/Text/Image")

Rel_R(integrator,artificialIntelligence,"Text prompt")
Rel_L(artificialIntelligence,integrator,"Response")

BiRel_L(authentication,dialogFlow,"User authentication")

BiRel_U(integrator,dialogFlow,"text\n-speech")

BiRel_U(external,integrator,"Request/Response")
BiRel_L(integrator,storage,"Read/Write")
SHOW_LEGEND(false)

@enduml
